
####################################
###############  H2  ###############
####################################

quarkus.datasource.jdbc.url=jdbc:h2:mem:default
quarkus.datasource.db-kind=h2
quarkus.hibernate-orm.database.generation=drop-and-create

####################################
######## Message Connector  ########
####################################

#   PRODUCER   #

mp.messaging.outgoing.request-out.connector=smallrye-kafka
mp.messaging.outgoing.request-out.topic=request.v1
mp.messaging.outgoing.request-out.value.serializer=org.apache.kafka.common.serialization.StringSerializer

#   CONSUMER   #

mp.messaging.incoming.diet-requests.connector=smallrye-in-memory
