
####################################
###############  H2  ###############
####################################

quarkus.datasource.jdbc.url=jdbc:h2:mem:default
quarkus.datasource.db-kind=h2
quarkus.hibernate-orm.database.generation=drop-and-create

####################################
######## Message Connector  ########
####################################

#   PRODUCER   #

mp.messaging.outgoing.diet-responses.connector=smallrye-in-memory

#   CONSUMER   #

mp.messaging.incoming.diet-requests.connector=smallrye-in-memory
