
####################################
###########  POSTGRESQL  ###########
####################################


####################################
############## OLLAMA ##############
####################################


quarkus.langchain4j.ollama.base-url=http://localhost:11434
quarkus.langchain4j.ollama.chat-model.model-id=llama3.2
quarkus.langchain4j.ollama.timeout=60s
quarkus.langchain4j.log-requests=true
quarkus.langchain4j.log-responses=true



####################################
################ MCP ###############
####################################

quarkus.langchain4j.mcp.patient-server.transport-type=http
quarkus.langchain4j.mcp.patient-server.url=http://localhost:8081/mcp/sse

####################################
############ GUARDRAILS ############
####################################

quarkus.langchain4j.guardrails.max-retries=3
